### PR TITLE
Add CRD Upgrade Safety preflight check

### LINKED ISSUE #909: Add a basic `CRDUpgradeSafety` preflight check
Following the merge of https://github.com/carvel-dev/carvel/pull/729, create a basic `CRDUpgradeSafety` preflight check to be added to `kapp deploy ...`.

Ideally, this is implemented in a way that makes it easy to iterate on and add new validations against CRD upgrades.

### PR DESCRIPTION
**Pull request by everettraven**
#### What this PR does / why we need it:
Adds an initial implementation of https://github.com/carvel-dev/carvel/pull/729

Includes the new `CRDUpgradeSafety` preflight check implementation and 2 of the known breaking changes during a CRD upgrade:
- Scope change (i.e cluster <--> namespace)
- Removal of existing stored version

Implementation is broken down into individual commits for review purposes, I am happy to squash commits before merging:
- Initial, generic preflight check implementation: https://github.com/carvel-dev/kapp/pull/901/commits/c2a34a5b8928c78a4cb6a8a9161a1eb00ce19f9a
- Scope change validation: https://github.com/carvel-dev/kapp/pull/901/commits/228ead697b626f8f95692cef2f1500ae87cba2a4
- Stored version validation: https://github.com/carvel-dev/kapp/pull/901/commits/28d60940e2e7cdc59645285668ab60927b6fcdd7

#### Which issue(s) this PR fixes:

Fixes #909 

#### Does this PR introduce a user-facing change?

```release-note
Adds an initial `CRDUpgradeSafety` preflight check implementation with checks to ensure a CRD upgrade does not include a scope change and/or removal of existing stored versions
```

##### Review Checklist:

- [ ] Follows the [developer guidelines](https://carvel.dev/shared/docs/latest/development_guidelines/)
- [ ] Relevant tests are added or updated
- [ ] Relevant docs in this repo added or updated
- [ ] Relevant carvel.dev docs added or updated in a separate PR and there's
  a link to that PR
- [ ] Code is at least as readable and maintainable as it was before this
  change

#### Additional documentation e.g., Proposal, usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by everettraven** [comment]
Note: I'm planning to squash commits prior to merging, but after reviews have been done to keep it easier to review

**Comment by everettraven** [comment]
> Note: I'm planning to squash commits prior to merging, but after reviews have been done to keep it easier to review

Whelp a botched rebase caused some problems that ended up in me deciding a squash after the rebase would be cleaner than the individual commits. Apologies to the reviewers!

**Review by praveenrewar — COMMENTED** [review]
LGTM! Thank you so much for making kapp better ❤️ 
I think a rebase would be required as Todd's PR is merged.

**Review by praveenrewar — APPROVED** [review]

**Comment by everettraven** [comment]
Thanks @praveenrewar ! I've just rebased, updated, and squashed the commits. Should be ready to merge!

The update made was https://github.com/carvel-dev/kapp/pull/901/files#diff-02d1be65fcbbdbd73025e5327506d584006201a288ba1c598b92e7d67467529eR52-R54 to satisfy the change to the `preflight.Check` interface Todd had made.

**Pull request merged**
