### PR TITLE
Remove go tidy from release step

### PR DESCRIPTION
**Pull request by joaopapereira**
Bump goreleaser to the latest version

### CODE REVIEW

**Review by praveenrewar — APPROVED** [review]
LGTM! 🙏🏻 
Since we are planning to replicate this for other tools, should we test this on a fork once? (Ignore if already done)

**Comment by rohitagg2020** [comment]
LGTM. Want to understand why we removed `go tidy` and `go vendor` from release process?

**Comment by joaopapereira** [comment]
When we are releasing our tools we want to make sure nothing changes. That is why we are removing those 2 steps

**Comment by kumaritanushree** [comment]
LGTM

**Review by sethiyash — APPROVED** [review]

**Pull request merged**
