### PR TITLE
WIP: move dependencies to Go modules

### LINKED ISSUE #64: Consider migrating to go modules
I found some stuff in pkg/* very interesting and usable, but sadly I cannot use it since the types in vendor/ of this repo conflicts with the Kubernetes api-machinery types I use through Go modules.
Hope you consider fixing.

```
go get github.com/k14s/kapp/pkg/kapp/resources
go: finding github.com/cppforlife/go-cli-ui latest
go: finding github.com/mattn/go-isatty v0.0.11
go: downloading github.com/mattn/go-isatty v0.0.11
go: extracting github.com/mattn/go-isatty v0.0.11
go: finding github.com/mattn/go-colorable v0.1.4
go: downloading github.com/mattn/go-colorable v0.1.4
go: extracting github.com/mattn/go-colorable v0.1.4
# github.com/k14s/kapp/pkg/kapp/resources
../../go/pkg/mod/github.com/k14s/kapp@v0.16.0/pkg/kapp/resources/resources.go:208:36: not enough arguments in call to resClient.Create
	have (*unstructured.Unstructured)
	want (*unstructured.Unstructured, "k8s.io/apimachinery/pkg/apis/meta/v1".CreateOptions, ...string)
../../go/pkg/mod/github.com/k14s/kapp@v0.16.0/pkg/kapp/resources/resources.go:238:36: not enough arguments in call to resClient.Update
	have (*unstructured.Unstructured)
	want (*unstructured.Unstructured, "k8s.io/apimachinery/pkg/apis/meta/v1".UpdateOptions, ...string)
../../go/pkg/mod/github.com/k14s/kapp@v0.16.0/pkg/kapp/resources/resources.go:265:35: not enough arguments in call to resClient.Patch
	have (string, types.PatchType, []byte)
	want (string, types.PatchType, []byte, "k8s.io/apimachinery/pkg/apis/meta/v1".PatchOptions, ...string)
```

### PR DESCRIPTION
**Pull request by rochacon**
After solving #61 it was simple to move to Go modules.

This PR attempts to remove `dep` and dependency vendoring, relying solely on Go modules for dependency management.

Closes #64

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@rochacon Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=k14s/kapp&pullRequestId=68)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=k14s/kapp&pullRequestId=68) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@rochacon Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=k14s/kapp&pullRequestId=68)!

**Comment by cppforlife** [comment]
will try to pull this in today.

**Comment by cppforlife** [comment]
pulled in your change, but ended up making few changes to avoid yaml version bump in this commit: https://github.com/k14s/kapp/commit/bf9dd0ecd8534ad37bae846599ff628a4ad65c4f

**Pull request closed without merging**
