### PR TITLE
kapp app-group deploy should order based on folder names

### LINKED ISSUE #755: `kapp app-group deploy` should order based on folder names
**What steps did you take:**
Deploy any app using `kapp app-group deploy`

**What happened:**
App deployment order is randomized on every execution.

**What did you expect:**
App deployment order should be alphabetically based on folder names.

**Anything else you would like to add:**
When reading directory using `ioutil.ReadDir` the ordering is correct, but when assigning to the result map here: https://github.com/carvel-dev/kapp/blob/df3cfc8d74bf79d52e96f8d1c1296d6f553f048b/pkg/kapp/cmd/appgroup/deploy.go#L137 ordering gets randomized.

**Environment:**

- kapp version (use `kapp --version`): 0.56.0
- OS (e.g. from `/etc/os-release`): macOS Ventura
- Kubernetes version (use `kubectl version`) 1.25.7

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

### PR DESCRIPTION
**Pull request by rjtch**
#### Which issue(s) this PR fixes:

Fixes #755 

#### Does this PR introduce a user-facing change?

```release-note

```

##### Review Checklist:

- [x] Follows the [developer guidelines](https://carvel.dev/shared/docs/latest/development_guidelines/)
- [x] Relevant tests are added or updated
- [x] Relevant docs in this repo added or updated
- [x] Relevant carvel.dev docs added or updated in a separate PR and there's
  a link to that PR
- [x] Code is at least as readable and maintainable as it was before this
  change

#### Additional documentation e.g., Proposal, usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by praveenrewar** [comment]
@rjtch DCO check is still failing, could you squash your commits and then sign the final commit?

**Comment by rjtch** [comment]
> @rjtch DCO check is still failing, could you squash your commits and then sign the final commit?

I don't find any solution I tried to fix it using git commit -s --amend and git commit -s -m but it did not work!!!

**Comment by praveenrewar** [comment]
@rjtch Could you make sure that the user name and the email in the signed off message are the ones that are linked to your account?

**Comment by praveenrewar** [comment]
@rjtch The DCO bot is happy now. I do see 9 commits but I don't seen any files getting changed 🤔

**Comment by rjtch** [comment]
> @rjtch The DCO bot is happy now. I do see 9 commits but I don't seen any files getting changed 🤔

Maybe through to much rebase things got lost. I will fix it.

**Review by praveenrewar — APPROVED** [review]
LGTM! Thank you so much for the contribution @rjtch

**Pull request merged**
